# single fidelity function


In [1]:
from mfpml.design_of_experiment.singlefideliy_samplers import LatinHyperCube
from mfpml.problems.singlefidelity_functions import Forrester
from mfpml.problems.multifidelity_functions import Forrester_1b
import numpy as np

In [2]:
# define function
function = Forrester()

print(function.input_domain)
# test sampling part
sampler = LatinHyperCube(design_space=function.input_domain)
sample_x = sampler.get_samples(num_samples=2, seed=1)
print(sample_x)

[[0. 1.]]
[[0.24408919]
 [0.52476815]]


In [3]:

sample_y = function.f(np.array([0.5]))
print(sample_y)

[[0.90929743]]


# Multi-fidelity functions


In [4]:
# define function
from mfpml.design_of_experiment.multifidelity_samplers import MFSobolSequence
function = Forrester_1b()
design_space = function.input_domain
# test sampling part
sampler = MFSobolSequence(design_space=design_space,
                          num_fidelity=2, nested=True)
samples = sampler.get_samples(num_samples=[4, 11])
print(samples)

[array([[0.55950899],
       [0.97013411],
       [0.26676969],
       [0.40537555]]), array([[5.59508991e-01],
       [9.70134110e-01],
       [2.66769687e-01],
       [4.05375551e-01],
       [8.58749396e-01],
       [6.74656789e-01],
       [6.50634468e-02],
       [7.38997944e-04],
       [7.34891860e-01],
       [7.93954002e-01],
       [4.66081672e-01]])]


In [5]:
sample_y = function(X=samples)

In [6]:
sample_y

[array([[ 0.76349455],
        [14.27057189],
        [-0.11428505],
        [ 0.14214545]]),
 array([[-4.02316281],
        [ 6.83662705],
        [-7.38944566],
        [-5.87517176],
        [-1.30415088],
        [-4.96440515],
        [-9.24888108],
        [-8.49730964],
        [-5.53718063],
        [-4.67968572],
        [-5.02206314]])]

In [ ]:
# test functions
from mfpml.problems.multifidelity_functions import (
    Forrester_1a, Forrester_1b, Forrester_1c, mf_Sixhump, mf_Hartman3, mf_Hartman6, mf_Discontinuous)

In [ ]:
forrester1a = Forrester_1a(num_dim=1)
# design space
design_space = forrester1a.design_space
best_value = forrester1a.optimum
sample_y = {}
sample_y["hf"] = forrester1a.hf(samples["hf"])
sample_y["lf"] = forrester1a.lf(samples["lf"])
print(design_space)
print(best_value)

In [ ]:
forrester1b = Forrester_1b(num_dim=1)
# design space
design_space = forrester1b.design_space
best_value = forrester1b.optimum
sample_y = {}
sample_y["hf"] = forrester1b.hf(samples["hf"])
sample_y["lf"] = forrester1b.lf(samples["lf"])
print(design_space)
print(design_space)
print(best_value)

In [ ]:
forrester1c = Forrester_1c(num_dim=1)
# design space
design_space = forrester1c.design_space
best_value = forrester1c.optimum
sample_y = {}
sample_y["hf"] = forrester1c.hf(samples["hf"])
sample_y["lf"] = forrester1c.lf(samples["lf"])
print(design_space)
print(best_value)

In [ ]:
mf_Disc = mf_Discontinuous(num_dim=1)
# design space
design_space = mf_Disc.design_space
best_value = mf_Disc.optimum
sample_y = {}
sample_y["hf"] = mf_Disc.hf(samples["hf"])
sample_y["lf"] = mf_Disc.lf(samples["lf"])
print(design_space)
print(best_value)

In [ ]:
# test functions
from mfpml.problems.multifidelity_functions import ContinuousNonlinearCorrelation1D

function = ContinuousNonlinearCorrelation1D(num_dim=1)
# design space
design_space = function.design_space
best_value = function.optimum
sample_y = {}
sample_y["hf"] = function.hf(samples["hf"])
sample_y["lf"] = function.lf(samples["lf"])
print(design_space)
print(best_value)

In [ ]:
# test functions
from mfpml.problems.multifidelity_functions import PhaseShiftedOscillations

function = PhaseShiftedOscillations(num_dim=1)
# design space
design_space = function.design_space
best_value = function.optimum
sample_y = {}
sample_y["hf"] = function.hf(samples["hf"])
sample_y["lf"] = function.lf(samples["lf"])
print(design_space)
print(best_value)

In [ ]:
mf_sixhum = mf_Sixhump(num_dim=2)
# design space
design_space = mf_sixhum.design_space
best_value = mf_sixhum.optimum

print(design_space)
print(best_value)

In [ ]:
sampler = MFSobolSequence(design_space=design_space, seed=12, nested=True)
samples = sampler.get_samples(num_lf_samples=10, num_hf_samples=4)
sampler.plot_samples(figsize=(3.5, 3.5))

In [ ]:
sample_y = {}
sample_y["hf"] = mf_sixhum.hf(samples["hf"])
sample_y["lf"] = mf_sixhum.lf(samples["lf"])
print(sample_y)