# single fidelity function


In [1]:
from mfpml.design_of_experiment.sf_samplers import LatinHyperCube
from mfpml.problems.sf_functions import Forrester
from mfpml.problems.mf_functions import Forrester_1b
import numpy as np

In [2]:
# define function
function = Forrester()

print(function.input_domain)
# test sampling part
sampler = LatinHyperCube(design_space=function.input_domain)
sample_x = sampler.get_samples(num_samples=2,
                               seed=1)
print(sample_x)

[[0. 1.]]
[[0.24408919]
 [0.52476815]]


In [3]:
from mfpml.problems.functions import Functions
# assert function belongs to Functions
assert isinstance(function, Functions)

In [4]:

sample_y = function.f(np.array([0.5]))
print(sample_y)

[[0.90929743]]


# Multi-fidelity functions


In [5]:
# define function
from mfpml.design_of_experiment.mf_samplers import MFSobolSequence
function = Forrester_1b()
design_space = function.input_domain
# test sampling part
sampler = MFSobolSequence(design_space=design_space,
                          num_fidelity=2, nested=True)
samples = sampler.get_samples(num_samples=[4, 11])
print(samples)

[array([[0.55950899],
       [0.97013411],
       [0.26676969],
       [0.40537555]]), array([[5.59508991e-01],
       [9.70134110e-01],
       [2.66769687e-01],
       [4.05375551e-01],
       [8.58749396e-01],
       [6.74656789e-01],
       [6.50634468e-02],
       [7.38997944e-04],
       [7.34891860e-01],
       [7.93954002e-01],
       [4.66081672e-01]])]


In [6]:
sample_y = function(X=samples)

In [7]:
sample_y

[array([[ 0.76349455],
        [14.27057189],
        [-0.11428505],
        [ 0.14214545]]),
 array([[-4.02316281],
        [ 6.83662705],
        [-7.38944566],
        [-5.87517176],
        [-1.30415088],
        [-4.96440515],
        [-9.24888108],
        [-8.49730964],
        [-5.53718063],
        [-4.67968572],
        [-5.02206314]])]

In [8]:
# test functions
from mfpml.problems.mf_functions import (
    Forrester_1a, Forrester_1b, Forrester_1c, mf_Sixhump, mf_Hartman3, mf_Hartman6, mf_Discontinuous)

In [9]:
forrester1a = Forrester_1a(num_dim=1)
# design space
design_space = forrester1a.input_domain
best_value = forrester1a.optimum
sample_y = {}
sample_y[0] = forrester1a.hf(samples[0])
sample_y[1] = forrester1a.lf(samples[1])
print(design_space)
print(best_value)

[[0. 1.]]
-6.02074
