# single fidelity samplers


In [2]:
# import the mfpml package
import numpy as np
from mfpml.design_of_experiment.sf_samplers import (
    LatinHyperCube,
    SobolSequence,
    RandomSampler,
    FixNumberSampler,
)
from mfpml.design_of_experiment.mf_samplers import (
    MFLatinHyperCube,
    MFSobolSequence,
)

In [3]:
# test the sf Sobol-Sequence sampler
design_space = np.array([[0, 1], [0, 1]])
sampler = SobolSequence(design_space=design_space)
samples = sampler.get_samples(num_samples=10, seed=1)
print(samples)

[[0.61334558 0.85919208]
 [0.42347366 0.34349881]
 [0.25498285 0.93772795]
 [0.68814827 0.48470276]
 [0.98263801 0.73930111]
 [0.04252389 0.19276982]
 [0.1168614  0.75236035]
 [0.92392461 0.29884688]
 [0.65286282 0.55405558]
 [0.33714239 0.00703601]]


In [4]:
# test the sf LatinHyperCube sampler
sampler = LatinHyperCube(design_space=design_space)
samples = sampler.get_samples(num_samples=10, seed=1)
print(samples)

[[0.84881784 0.70495363]
 [0.98558404 0.50513506]
 [0.26881685 0.85766736]
 [0.41722974 0.45908009]
 [0.04504063 0.09724409]
 [0.62464869 0.64618567]
 [0.76702683 0.12115713]
 [0.56968052 0.25465021]
 [0.18659583 0.3596887 ]
 [0.37965448 0.97376867]]


In [5]:
# test the sf Random sampler
sampler = RandomSampler(design_space=design_space)
samples = sampler.get_samples(num_samples=10, seed=11)
print(samples)

[[0.18026969 0.01947524]
 [0.46321853 0.72493393]
 [0.4202036  0.4854271 ]
 [0.01278081 0.48737161]
 [0.94180665 0.85079509]
 [0.72996447 0.10873607]
 [0.89390417 0.85715425]
 [0.16508662 0.63233401]
 [0.02048361 0.11673727]
 [0.31636731 0.15791231]]


# Multi-fidelity samplers


In [6]:
#
mf_sampler = MFSobolSequence(design_space=design_space,
                             num_fidelity=2,
                             nested=False)
samples = mf_sampler.get_samples(num_samples=[10, 20])

print(samples)

[array([[0.64763958, 0.28450888],
       [0.36683413, 0.68135563],
       [0.48028161, 0.47841079],
       [0.51099956, 0.61233338],
       [0.92215368, 0.08658168],
       [0.07887466, 0.93974256],
       [0.01998916, 0.35459914],
       [0.98921781, 0.73632443],
       [0.57812486, 0.21319705],
       [0.42133521, 0.81318406]]), array([[0.64763958, 0.28450888],
       [0.36683413, 0.68135563],
       [0.48028161, 0.47841079],
       [0.51099956, 0.61233338],
       [0.92215368, 0.08658168],
       [0.07887466, 0.93974256],
       [0.01998916, 0.35459914],
       [0.98921781, 0.73632443],
       [0.57812486, 0.21319705],
       [0.42133521, 0.81318406],
       [0.29992609, 0.01648945],
       [0.70661298, 0.88477179],
       [0.85214304, 0.40789327],
       [0.13289509, 0.5579139 ],
       [0.18038307, 0.39822532],
       [0.83616588, 0.51286079],
       [0.72186917, 0.03761379],
       [0.25364737, 0.93398755],
       [0.40607283, 0.23067839],
       [0.6243745 , 0.86605055]])]


In [7]:
# mf sobol sequence with non-nested sampling
mf_sampler = MFLatinHyperCube(design_space=design_space,
                              num_fidelity=2,
                              nested=False)
samples = mf_sampler.get_samples(num_samples=[10, 20])
print(samples)

[array([[0.33634863, 0.66151883],
       [0.49525546, 0.30447473],
       [0.90939491, 0.45430304],
       [0.07194665, 0.73638512],
       [0.60192893, 0.91875682],
       [0.26948018, 0.5431989 ],
       [0.19793128, 0.84268995],
       [0.55878087, 0.06547125],
       [0.8269548 , 0.27182701],
       [0.79776655, 0.17487075]]), array([[9.10584347e-01, 4.00165504e-04],
       [1.52071585e-01, 4.06114726e-01],
       [2.66937071e-01, 6.44535336e-01],
       [5.02119839e-01, 8.78273269e-01],
       [8.33313950e-01, 2.37428010e-01],
       [8.05247788e-02, 7.34285587e-01],
       [4.38314145e-01, 4.85537058e-01],
       [8.86217469e-01, 5.84025470e-01],
       [3.86654209e-01, 2.67416199e-01],
       [4.37746268e-02, 1.05093740e-01],
       [7.23630206e-01, 5.17477294e-01],
       [5.71098997e-01, 9.10327013e-01],
       [9.78328341e-01, 1.92889205e-01],
       [1.04854690e-01, 3.47123776e-01],
       [6.12496747e-01, 9.67531025e-01],
       [3.41199641e-01, 9.61833407e-02],
       [4.7